import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.style import context
import sys

sys.path.insert(1, "/home/koen/LaTeX-setup/python-files/")
from plot_size import set_size

column = 312.98032
full = 483.69684
plt.style.use("default")
plt.style.use("tex rm")

sys.path.insert(1, "/home/koen/master-internship/")
from scripts.general_utils.cplot import cplot
from scripts.general_utils.cache import get_star

plt.cplot = cplot


# %%

qs = np.arange(0.05, 1.05, 0.05)
rs = np.arange(100, 1260, 10)
# size calculation

qs2 = np.linspace(0.4, 0.7, 4)
qs = [0.4000, 0.4293, 0.6356, 0.6511, 0.7000]
ms = [3, 2.6, 2.2, 1.8]

qqs, mms = np.meshgrid(qs, ms)
qqs2, mms2 = np.meshgrid(qs2, ms)

plt.pcolormesh(qqs, mms, qqs * mms, cmap="viridis")
plt.show()


# %%


masses = qqs * mms
masses2 = qqs2 * mms2
masses = masses.flatten()
masses2 = masses2.flatten()
masses.sort()
masses2.sort()
# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column, height=0.3), constrained_layout=True
)


print(d)

plt.scatter(masses[::2], masses[::2] * 0 + 0.05, s=1.5, marker="o", color="k")
plt.scatter(masses[1::2], masses[1::2] * 0 - 0.05, s=1.5, marker="o", color="k")
plt.scatter(masses2[::2], masses2[::2] * 0 + 1.05, s=1.5, marker="o", color="k")
plt.scatter(masses2[1::2], masses2[1::2] * 0 + 0.95, s=1.5, marker="o", color="k")
# plt.scatter(mild["[Fe/H]"], mild["[Fe/H]"] * 0 + 1, s=1.5, marker="o", color="k")
# plt.scatter(strong["[Fe/H]"], strong["[Fe/H]"] * 0 + 2, s=1.5, marker="o", color="k")

axs.spines[["right", "top", "left"]].set_visible(False)
axs.tick_params(axis="y", which="both", length=0)
plt.xlim(0.7, 2.1)
plt.xticks([0.7, 1, 1.25, 1.5, 1.75, 2.1])

plt.xlabel("[Fe/H]")
labels = ["\\textit{un}equal $q$ spacing", "equal $q$ spacing"]
plt.yticks([0, 1], labels)
plt.ylim(-0.5, 1.5)
plt.savefig("/home/koen/LaTeX-setup/plots/w24-scatter.pgf", format="pgf")
plt.show()
plt.close()


# %%

print(np.linspace(500, 1200, 8))


# %%

8 * 4 * 5
# %%

import numpy as np
from scipy.optimize import differential_evolution

donor_masses = np.array([3.0, 2.6, 2.2, 1.8])


def accretor_masses(q):
    """Return all initial accretor masses for a set of q values."""
    return np.sort(np.outer(q, donor_masses).ravel())


def objective(q_interior):
    """Variance of the spacings between sorted accretor masses."""
    q = np.r_[0.4, np.sort(q_interior), 0.7]

    masses = accretor_masses(q)
    spacings = np.diff(masses)

    return np.var(spacings)


def optimize_q(n):
    """
    Find n q values between 0.4 and 0.7.

    q=0.4 and q=0.7 are always included.
    """

    if n < 2:
        raise ValueError("n must be at least 2")

    if n == 2:
        return np.array([0.4, 0.7])

    result = differential_evolution(
        objective,
        bounds=[(0.4, 0.7)] * (n - 2),
        tol=1e-10,
        polish=True,
        seed=42,
    )

    return np.r_[
        0.4,
        np.sort(result.x),
        0.7,
    ]


# example
n = 5

q = optimize_q(n)

print("q values:")
print(q)

masses = accretor_masses(q)

print("\naccretor masses:")
print(masses)

print("\nspacings:")
print(np.diff(masses))

print("\nvariance:")
print(np.var(np.diff(masses)))
# %%
import numpy as np
from scipy.optimize import differential_evolution

donor_masses = np.array([3.0, 2.6, 2.2, 1.8])

q_min = 0.4
q_max = 0.7


def min_mass_separation(q_interior):
    """
    Return the minimum separation between any two initial
    accretor masses generated by the q values.
    """

    q = np.r_[q_min, np.sort(q_interior), q_max]

    # all combinations of q and donor mass
    accretor_masses = np.outer(q, donor_masses).ravel()

    # sort them so consecutive differences give the spacings
    accretor_masses.sort()

    return np.min(np.diff(accretor_masses))


q_min_separation = 0.01


def objective(q_interior):
    q = np.r_[q_min, np.sort(q_interior), q_max]

    if np.min(np.diff(q)) < q_min_separation:
        return 1e3

    accretor_masses = np.outer(q, donor_masses).ravel()
    accretor_masses.sort()

    return -np.min(np.diff(accretor_masses))


def optimize_q(n, seed=42):
    """
    Find n q values between q_min and q_max that maximize
    the minimum separation between all resulting accretor masses.

    The endpoints q_min and q_max are always included.
    """

    if n < 2:
        raise ValueError("n must be at least 2")

    if n == 2:
        return np.array([q_min, q_max])

    result = differential_evolution(
        objective,
        bounds=[(q_min, q_max)] * (n - 2),
        seed=seed,
        polish=True,
        tol=1e-10,
        workers=1,
    )

    q = np.r_[
        q_min,
        np.sort(result.x),
        q_max,
    ]

    return q


# %%
n = 25

q = optimize_q(n)

print(q)
print("minimum separation:", min_mass_separation(q[1:-1]))

# %%
qs = np.arange(0.05, 1.05, 0.05)
rs = np.arange(100, 1260, 10)

from pathlib import Path
import pickle
from matplotlib.collections import LineCollection
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Rectangle

DATA_DIR = Path("scripts/w23")


# helpers


def load_mass_data(mass):
    """Load all W23 grid data for a given TP-AGB mass."""

    names = [
        "possible",
        "eps_max",
        "eps_min",
        "co",
        "dup",
        "min_mass",
        "max_mass",
        "wind_accretion",
    ]

    for fmt in [f"{mass}", f"{mass:.1f}"]:
        try:
            data = {}

            for name in names:
                path = DATA_DIR / f"const_mass_{name}_{fmt}_small.pkl"

                with open(path, "rb") as f:
                    data[name] = pickle.load(f)

            return data

        except FileNotFoundError:
            continue

    raise FileNotFoundError(f"could not find data for mass {mass}")


def plot_panel(ax, co_matrix, eps_matrix, x, y, norm, cmap):
    """Plot one CO-ratio / epsilon-region panel."""

    ax.pcolormesh(
        x,
        y,
        co_matrix.T,
        shading="nearest",
        cmap=cmap,
        norm=norm,
        rasterized=True,
    )

    draw_region_boundaries(
        ax,
        eps_matrix.T,
        x,
        y,
        colors={
            (0, 0.5): "magenta",
            (0.5, 1): "black",
            (0, 1): "lime",
        },
    )

    ax.contourf(
        x,
        y,
        eps_matrix.T,
        colors="none",
        hatches=["||", None, None, None],
        corner_mask=False,
        rasterized=True,
    )


def plot_by_mass(
    data, variable, masses, rs, qs, norm, cmap, figsize=full, figheight=1.8, ncols=3
):
    ncols = ncols
    nrows = int(np.ceil(len(masses) / ncols))

    fig, axs = plt.subplots(
        nrows,
        ncols,
        sharex=True,
        sharey=True,
        figsize=set_size(figsize, height=figheight),
        constrained_layout=True,
    )

    axs = np.atleast_1d(axs).flatten()

    for ax, mass in zip(axs, masses):
        d = data[mass]

        plot_panel(
            ax,
            d[variable],
            d["possible"],
            rs,
            qs,
            norm,
            cmap,
        )

        ax.set_title(f"$M_{{\\rm TPAGB}} = {mass:.1f}$")

    for ax in axs[len(masses) :]:
        ax.axis("off")

    return fig, axs


def get_q_slice(data, variable, masses, q_index):
    """Return CO and epsilon grids for a fixed q."""

    co = np.array([data[mass][variable][:, q_index] for mass in masses]).T

    eps = np.array([data[mass]["possible"][:, q_index] for mass in masses]).T

    return co, eps


def plot_by_q(
    data,
    variable,
    masses,
    qs,
    rs,
    norm,
    cmap,
    figsize=full,
    figheight=1.8,
    ncols=3,
    q_index_offset=0,
):
    ncols = ncols
    nrows = int(np.ceil(len(qs) / ncols))

    fig, axs = plt.subplots(
        nrows,
        ncols,
        sharex=True,
        sharey=True,
        figsize=set_size(figsize, height=figheight),
        constrained_layout=True,
    )

    axs = np.atleast_1d(axs).flatten()

    for ax, q_index, q in zip(axs, range(len(qs)), qs):

        co, eps = get_q_slice(data, variable, masses, q_index + q_index_offset)

        plot_panel(
            ax,
            co,
            eps,
            rs,
            masses,
            norm,
            cmap,
        )

        ax.set_title(f"$q = {q:.2f}$")

    for ax in axs[len(qs) :]:
        ax.axis("off")

    return fig, axs


def add_colorbar(fig, ax, norm, cmap, label, aspect=20):
    sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])

    cbar = plt.colorbar(
        sm, ax=ax, orientation="horizontal", location="top", aspect=aspect
    )
    cbar.ax.set_xscale("linear")

    cbar.set_label(label)

    return cbar


def draw_region_boundaries(
    ax,
    region,
    x,
    y,
    colors=None,
    linewidth=2,
):
    """
    Draw blocky boundaries between discrete regions.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    region : 2D ndarray
        Region labels (e.g. 0, 0.5, 1).
        Shape must match the pcolormesh array.
    x, y : 1D arrays
        Grid coordinates used by pcolormesh.
    colors : dict, optional
        Dictionary mapping region pairs to colors.
        Example:
        {
            (0, 0.5): "red",
            (0.5, 1): "blue",
            (0, 1): "green",
        }
    linewidth : float
        Line width.
    """

    if colors is None:
        colors = {
            (0, 0.5): "red",
            (0.5, 1): "blue",
            (0, 1): "black",
        }

    segments = []
    segment_colors = []

    ny, nx = region.shape

    # vertical boundaries
    for j in range(ny):
        for i in range(nx - 1):
            a = region[j, i]
            b = region[j, i + 1]

            if a != b:
                pair = tuple(sorted((a, b)))
                if pair in colors:
                    segments.append(
                        [
                            (0.5 * (x[i] + x[i + 1]), y[j] - 0.5 * (y[1] - y[0])),
                            (0.5 * (x[i] + x[i + 1]), y[j] + 0.5 * (y[1] - y[0])),
                        ]
                    )
                    segment_colors.append(colors[pair])

    # horizontal boundaries
    for j in range(ny - 1):
        for i in range(nx):
            a = region[j, i]
            b = region[j + 1, i]

            if a != b:
                pair = tuple(sorted((a, b)))
                if pair in colors:
                    segments.append(
                        [
                            (x[i] - 0.5 * (x[1] - x[0]), 0.5 * (y[j] + y[j + 1])),
                            (x[i] + 0.5 * (x[1] - x[0]), 0.5 * (y[j] + y[j + 1])),
                        ]
                    )
                    segment_colors.append(colors[pair])

    lc = LineCollection(
        segments,
        colors=segment_colors,
        linewidths=linewidth,
        capstyle="butt",
        joinstyle="miter",
        rasterized=True,
        label="test",
    )

    ax.add_collection(lc)

    return lc


# %%
variable = "dup"

# loading data
masses = np.arange(1.0, 3.05, 0.1)
qs = np.arange(0.40, 0.75, 0.05)
rs = np.arange(100, 1260, 10)
data = {m: load_mass_data(m) for m in masses}

# color normalisation
minn = np.min([np.nanmin(d[variable]) for d in data.values()])
maxx = np.max([np.nanmax(d[variable]) for d in data.values()])

# norm = TwoSlopeNorm(vcenter=1, vmin=minn, vmax=maxx)
norm = plt.Normalize(minn, maxx)
cmap = plt.cm.viridis

fig, axs = plot_by_q(
    data,
    variable,
    masses,
    qs,
    rs,
    norm,
    cmap,
    ncols=2,
    q_index_offset=7,
    figsize=column,
)

false_array_1 = np.ones((len(masses), 41))
false_array_2 = np.ones((8, len(rs)))
false_array_3 = np.ones((len(masses), 6))

for ax in axs:
    if ax == axs[-1]:
        continue
    ax.set_xlim(ax.get_xlim())
    ax.set_ylim(ax.get_ylim())
    ax.plot([500, 500, 1200, 1200], [3, 1.8, 1.8, 3.1], c="r", linewidth=2)
    ax.contourf(
        rs[0:41],
        masses,
        false_array_1,
        shading="nearest",
        colors="none",
        hatches=["--", None, None, None],
        corner_mask=False,
        rasterized=True,
    )
    ax.contourf(
        rs,
        masses[0:8],
        false_array_2,
        shading="nearest",
        colors="none",
        hatches=["--", None, None, None],
        corner_mask=False,
        rasterized=True,
    )
    ax.contourf(
        rs[-6:],
        masses,
        false_array_3,
        shading="nearest",
        colors="none",
        hatches=["--", None, None, None],
        corner_mask=False,
        rasterized=True,
    )

# for ax in axs:
# ax.set_xlim(500, 1200)
#     ax.set_ylim(1.8, 3)

custom_lines = [
    Line2D([0], [0], color="magenta", lw=2),
    Line2D([0], [0], color="black", lw=2),
    Line2D([0], [0], color="lime", lw=2),
    Line2D([0], [0], color="red", lw=2),
    Rectangle((0, 0), 2, 2, fill=False, hatch="|||"),
    Line2D([0], [0], color="white", lw=2),
    Line2D([0], [0], color="white", lw=2),
    Line2D([0], [0], color="white", lw=2),
]

fig.supxlabel(r"Initial Roche lobe radius ($R_\odot$)", fontsize=10)
fig.supylabel(r"TPAGB mass ($M_\odot$)", fontsize=10)

fig.legend(
    custom_lines,
    [
        "Border between wind\nregime with possible and\nimpossible final masses",
        "Border between RLOF\nand wind only regime",
        "Border between RLOF\nregime with possible and\nimpossible final masses",
        "Border between possible and\nimpossible MESA models",
        "Impossible region",
        "",
        "",
        "",
    ],
    loc="lower right",
    ncols=1,
    borderpad=0,
    borderaxespad=0,
    # draggable=True,
    frameon=False,
)

fig.supylabel("Initial mass ratio ($q$)", fontsize=10)
fig.supxlabel("Initial Roche lobe radius ($R_\odot$)", fontsize=10)

add_colorbar(
    fig,
    axs[1:3],
    norm,
    cmap,
    label=r"$M_\textrm{DUP}$ at end of \texttt{evolve.py}",
    aspect=35,
)

plt.savefig("/home/koen/LaTeX-setup/plots/w24-mspace-dup.pgf", format="pgf")
plt.show()


# %%

sys.path.insert(1, "/home/koen/master-internship/")
MASTER = "/home/koen/master-internship/mesa-models/"
from scripts.general_utils.cplot import cplot

plt.cplot = cplot
import mesa_reader as mr
from scripts.general_utils.mesa_grid_2 import MesaGrid

# %%

grid = MesaGrid(f"{MASTER}const-ba-star-mass-grid")

# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

markers = ["*", "^", "s"]

norm = plt.Normalize(0, 1)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for d in grid.axes["delta"]:
    labels = []
    for i, eps in enumerate(grid.settings["eps"]):
        print(eps)

        dt_mins = []
        env_mass = []
        for model in grid.filter(f_delta=d, eps=eps):
            dt_mins.append(np.min(model.log_dt))
            env_mass.append(model.envelope_mass[-1])
        l = plt.scatter(
            dt_mins,
            env_mass,
            color=cmap(norm(d)),
            label=f"$\\varepsilon = {eps:.2f}$",
            marker=markers[i],
            s=10,
        )
        labels.append(l)


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

fig.legend(loc="outside upper center", ncols=4, handles=labels)
cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$\delta / (1-\varepsilon)$")

axs.spines[["right", "top"]].set_visible(False)
plt.yscale("log")
plt.xlabel(r"$\textrm{min}(\log(\Delta t / \textrm{yr})$")
plt.ylabel("Envelope mass at end of evolution ($M_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-minlogt.pgf", format="pgf")
plt.show()
plt.close()

# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

markers = ["*", "^", "s"]

norm = plt.Normalize(0, 1)
cmap = plt.cm.viridis
# color = cmap(norm(x))


min_model = grid.models[np.argmin([model.envelope_mass[-1] for model in grid.models])]
for d in grid.axes["delta"]:
    labels = []
    for i, eps in enumerate(grid.settings["eps"]):

        dt_mins = []
        env_mass = []
        for model in grid.filter(f_delta=d, eps=eps):
            dt_mins.append(model.R[-1])
            env_mass.append(model.envelope_mass[-1])
        l = plt.scatter(
            dt_mins,
            env_mass,
            color=cmap(norm(d)),
            label=f"$\\varepsilon = {eps:.2f}$",
            marker=markers[i],
            s=10,
        )
        labels.append(l)

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

fig.legend(loc="outside upper center", ncols=4, handles=labels)
cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$\delta / (1-\varepsilon)$")

axs.spines[["right", "top"]].set_visible(False)
plt.yscale("log")
plt.xlabel(r"$\textrm{min}(\log(\Delta t / \textrm{yr})$")
plt.ylabel(r"Envelope mass at end of evolution ($M_\odot$)")
# plt.savefig("/home/koen/LaTeX-setup/plots/w24-minlogt.pgf", format="pgf")
plt.show()
plt.close()


# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

print(min_model.bulk_names)
for d in grid.axes["delta"]:
    labels = []
    for model in grid.filter(f_delta=d, eps=grid.settings["eps"][0]):
        lc = plt.cplot(
            model.log_Teff, model.log_L, c=model.R / model.rl_1, cmap="viridis"
        )

plt.colorbar(lc)
axs.invert_xaxis()

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("")
plt.ylabel("")
plt.savefig("/home/koen/LaTeX-setup/plots/.pgf", format="pgf")
plt.show()
plt.close()
# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

markers = ["*", "^", "s"]

norm = plt.Normalize(0, 1)
cmap = plt.cm.viridis
# color = cmap(norm(x))


min_model = grid.models[np.argmin([model.envelope_mass[-1] for model in grid.models])]
for d in grid.axes["delta"]:
    labels = []
    for i, eps in enumerate(grid.settings["eps"]):

        dt_mins = []
        env_mass = []
        for model in grid.filter(f_delta=d, eps=eps):
            dt_mins.append(np.max(model.R / model.rl_1))
            env_mass.append(model.star_2_mass[-1] - model.star_2_mass[0])
        l = plt.scatter(
            env_mass,
            dt_mins,
            color=cmap(norm(d)),
            label=f"$\\varepsilon = {eps:.2f}$",
            marker=markers[i],
            s=10,
        )
        labels.append(l)

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

fig.legend(loc="outside upper center", ncols=4, handles=labels)
cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$\delta / (1-\varepsilon)$")

axs.spines[["right", "top"]].set_visible(False)
# plt.yscale("log")
plt.xlabel(r"$\textrm{min}(\log(\Delta t / \textrm{yr})$")
plt.ylabel(r"Envelope mass at end of evolution ($M_\odot$)")
# plt.savefig("/home/koen/LaTeX-setup/plots/w24-minlogt.pgf", format="pgf")
plt.show()
plt.close()


# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

print(min_model.bulk_names)
for d in grid.axes["delta"]:
    labels = []
    for model in grid.filter(f_delta=d, eps=grid.settings["eps"][0]):
        lc = plt.cplot(
            model.envelope_mass, model.R, c=model.R / model.rl_1, cmap="viridis"
        )

plt.colorbar(lc)
# axs.invert_xaxis()

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("")
plt.ylabel("")
# plt.savefig("/home/koen/LaTeX-setup/plots/.pgf", format="pgf")
plt.show()
plt.close()
# %%


def find_CO(r):
    if r.period_days[-1] < 50:
        return np.nan

    try:
        ind = np.argwhere(r.rl_1 < r.R)[0][0]
        return r.period_days[-1]
    except:
        return np.nan


fig, axs = plt.subplots(
    1, 1, sharey=True, figsize=set_size(full, height=0.5), constrained_layout=True
)

minn = 1e99
maxx = -1e-99


R, q, ratio = grid.array(
    find_CO,
    x="R",
    y="q",
)
minn = np.nanmin(ratio) if np.nanmin(ratio) < minn else minn
maxx = np.nanmax(ratio) if np.nanmax(ratio) > maxx else maxx


c = plt.pcolormesh(
    R,
    q,
    ratio.T,
    shading="auto",
    cmap="viridis",
    vmin=minn,
    vmax=maxx,
    rasterized=True,
)

plt.colorbar(
    c,
    ax=axs,
    orientation="horizontal",
    location="top",
    aspect=50,
    label="Observed CO-ratio (no mixing in barium star)",
)
plt.xlabel("")
plt.ylabel("")
# plt.savefig("/home/koen/LaTeX-setup/plots/w22-eps-hist-CO-no-mixing.pgf", format="pgf")
plt.show()
plt.close()
# %%

star = get_star(m=2.6)

# plt.plot(star.age, star.log_R)
# print(star.m_DUP_time)

for tp in np.unique(np.asarray(star.TP_count)[star.ntpagb :]):
    plt.plot(star.age, star.m_DUP_time[tp])
plt.plot(star.age, star.TP_count / 10000)
plt.plot(star.age, star.m_DUP_time[0])
plt.show()
# %%


TP_count = np.asarray(star.TP_count)[star.ntpagb :]
print(TP_count)
# %%

for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    plt.plot(star.age, star.m_DUP_time[0])
plt.show()
# %%


def mass_envelope_dredge_up_something(star):

    m_DUP_left = {}
    m_DUP_left[0] = 0 * star.m_DUP_time[0]
    for tp in np.unique(np.asarray(star.TP_count)[star.ntpagb :]):
        try:
            arg = np.argwhere(star.m_DUP_time[tp] > 0)[0][0]
            ref = star.m_env[arg]
            m_DUP_left[tp] = star.m_DUP_time[tp] * star.m_env / ref
            m_DUP_left[0] += star.m_DUP_time[tp] * star.m_env / ref
        except:
            m_DUP_left[tp] = star.m_DUP_time[tp]
    return m_DUP_left


# %%
norm = plt.Normalize(1, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    m_DUP_left = mass_envelope_dredge_up_something(star)

    plt.plot(
        star.age[star.ntpagb :] - star.age[star.ntpagb],
        m_DUP_left[0][star.ntpagb :],
        c=cmap(norm(m)),
    )


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"label")

plt.show()


# %%
norm = plt.Normalize(1, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    m_DUP_left = mass_envelope_dredge_up_something(star)

    plt.plot(
        star.m_env[star.ntpagb :],
        m_DUP_left[0][star.ntpagb :] / star.m_env[star.ntpagb :],
        c=cmap(norm(m)),
    )


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"label")

plt.show()


# %%
from matplotlib import ticker

norm = plt.Normalize(1, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    m_DUP_left = mass_envelope_dredge_up_something(star)

    plt.plot(
        star.age[star.ntpagb :] - star.age[star.ntpagb],
        star.m_DUP_time[0][star.ntpagb :],
        c=cmap(norm(m)),
    )


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"label")

# plt.gca().yaxis.set_major_formatter(ticker.PercentFormatter(1))
plt.show()


# %%

from matplotlib import ticker

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(1, np.nanmax(star.TP_count))
cmap = plt.cm.plasma
# color = cmap(norm(x))


m = 2.5
star = get_star(m=2.5)

for i, tp in enumerate(np.unique(star.TP_count[star.ntpagb :])):

    plt.plot(
        star.age[star.ntpagb :] - star.age[star.ntpagb],
        star.m_DUP_time[tp][star.ntpagb :],
        c=cmap(norm(tp)),
        linewidth=2 if i % 2 == 0 else 0.8,
    )

plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    star.m_DUP_time[0][star.ntpagb :],
    c="C2",
    linewidth=2,
    label="sum of individiual TDU events",
)

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"Thermal pulse count")

plt.yscale("log")

fig.legend(loc="outside upper center")

plt.text(
    0.05, 0.95, f"$M_\\textrm{{TPAGB, i}} = {2.5}\\;M_\\odot$", transform=axs.transAxes
)
plt.ylim(1e-7)

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time since TPAGB (yr)")
plt.ylabel(r"$M_\textrm{DUP}$ ($M_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-TDU-individual.pgf", format="pgf")
plt.show()
plt.close()


# %%

from matplotlib import ticker

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(1, np.nanmax(star.TP_count))
cmap = plt.cm.plasma
# color = cmap(norm(x))


m = 2.5
star = get_star(m=2.5)

m_DUP_left = mass_envelope_dredge_up_something(star)

# for i, tp in enumerate(np.unique(star.TP_count[star.ntpagb:])):
#
#     plt.plot(star.age[star.ntpagb:] - star.age[star.ntpagb], m_DUP_left[tp][star.ntpagb:], c = cmap(norm(tp)), linewidth=2 if i%2==0 else 0.8)

plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    m_DUP_left[0][star.ntpagb :],
    c="C0",
    label="Actual in envelope",
)
plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    star.m_DUP_time[0][star.ntpagb :],
    c="C1",
    label="TDU amount",
    zorder=-1,
)

plt.text(
    0.05, 0.95, f"$M_\\textrm{{TPAGB, i}} = {2.5}\\;M_\\odot$", transform=axs.transAxes
)
sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

# cbar = plt.colorbar(sm, ax=plt.gca())
# cbar.set_label(r"Thermal pulse count")

# plt.yscale("log")

fig.legend(loc="outside upper center", ncols=2)

plt.ylim(1e-7)

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time since TPAGB (yr)")
plt.ylabel(r"$M_\textrm{DUP}$ in enevelope ($M_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-TDU-left.pgf", format="pgf")
plt.show()
plt.close()


# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(1, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))

for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    m_DUP_left = mass_envelope_dredge_up_something(star)

    plt.plot(
        star.age[star.ntpagb :] - star.age[star.ntpagb],
        m_DUP_left[0][star.ntpagb :],
        c=cmap(norm(m)),
    )

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$M_\textrm{TPAGB, i}$ ($M_\odot$)")

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time since TPAGB (yr)")
plt.ylabel(r"$M_\textrm{DUP}$ in enevelope ($M_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-TDU-diff-masses.pgf", format="pgf")
plt.show()
plt.close()

# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

ms = np.arange(1, 3.05, 0.1)

age = []

for m in ms:
    star = get_star(m=m)
    age.append(star.age[-1] - star.age[star.ntpagb])

plt.plot(ms, age, c="k")
plt.scatter(ms, age, zorder=11, marker=".", c="k")
plt.scatter(ms, age, zorder=10, s=200, marker=".", c="white")

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel(r"Initial TPAGB mass ($M_\odot$)")
plt.ylabel("TPAGB age (yr)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-mass-tpagb-time.pgf", format="pgf")
plt.show()
plt.close()

# %%

from matplotlib import ticker

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(1, np.nanmax(star.TP_count))
cmap = plt.cm.plasma
# color = cmap(norm(x))


m = 2.5
star = get_star(m=2.5)

m_DUP_left = mass_envelope_dredge_up_something(star)

# for i, tp in enumerate(np.unique(star.TP_count[star.ntpagb:])):
#
#     plt.plot(star.age[star.ntpagb:] - star.age[star.ntpagb], m_DUP_left[tp][star.ntpagb:], c = cmap(norm(tp)), linewidth=2 if i%2==0 else 0.8)

plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    star.m_DUP_time[0][star.ntpagb :] - m_DUP_left[0][star.ntpagb :],
    c="C1",
    label="TDU amount",
    zorder=-1,
)

plt.text(
    0.05, 0.95, f"$M_\\textrm{{TPAGB, i}} = {2.5}\\;M_\\odot$", transform=axs.transAxes
)
sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

# cbar = plt.colorbar(sm, ax=plt.gca())
# cbar.set_label(r"Thermal pulse count")

# plt.yscale("log")

fig.legend(loc="outside upper center", ncols=2)

plt.ylim(1e-7)

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time since TPAGB (yr)")
plt.ylabel(r"$M_\textrm{DUP}$ in enevelope ($M_\odot$)")
# plt.savefig("/home/koen/LaTeX-setup/plots/w24-TDU-left.pgf", format="pgf")
plt.show()
plt.close()


# %%

dt = np.diff(star.age)
plt.plot(star.age[star.ntpagb :], star.m_env[star.ntpagb] - star.m_env[star.ntpagb :])
plt.plot(
    star.age[star.ntpagb :], np.cumsum(star.Mdot[star.ntpagb :] * dt[star.ntpagb - 1 :])
)
plt.show()

# %%

plt.plot(star.age[star.ntpagb :], star.m_core[star.ntpagb :])
plt.show()
# %%

print(star.m_core[-1] - star.m_core[star.ntpagb])
# %%

dt = np.diff(star.age)
plt.plot(
    star.age[star.ntpagb :], np.cumsum(star.Mdot[star.ntpagb :] * dt[star.ntpagb - 1 :])
)
plt.plot(star.age[star.ntpagb :], star.m_core[star.ntpagb :] - star.m_core[star.ntpagb])
plt.plot(star.age[star.ntpagb :], star.m_env[star.ntpagb :])
plt.show()


# %%
dt = np.diff(star.age)
dot_m_core = (np.diff(star.m_core) / dt)[star.ntpagb - 1 :]
dot_m_wind = star.Mdot[star.ntpagb :]


# %%

# input arrays from your mesa/model data
time = star.age[star.ntpagb :]
M_env = star.m_env[star.ntpagb :]
M_core = star.m_core[star.ntpagb :]
mdot_transfer = 0 * star.Mdot[star.ntpagb :]
mdot_wind = star.Mdot[star.ntpagb :]

TP_count = star.TP_count[star.ntpagb :]
M_DUP = star.m_DUP

# ----------------------------------------------------------------------
# storage
# ----------------------------------------------------------------------


n_times = len(time)
n_TP = len(M_DUP)

# mass from each TP currently remaining in the donor envelope
tracer = np.zeros(n_TP)

# cumulative fate of the material from each TP
accreted = np.zeros(n_TP)
wind_lost = np.zeros(n_TP)
core_lost = np.zeros(n_TP)

# optionally store the full history
tracer_history = np.zeros((n_TP, n_times))
accreted_history = np.zeros((n_TP, n_times))
wind_history = np.zeros((n_TP, n_times))
core_history = np.zeros((n_TP, n_times))


# ----------------------------------------------------------------------
# evolve through the stellar track
# ----------------------------------------------------------------------

for j in range(1, n_times):

    dt = time[j] - time[j - 1]

    # mass-loss rates should be positive here
    dm_transfer = mdot_transfer[j] * dt
    dm_wind = mdot_wind[j] * dt

    # core growth
    dm_core = M_core[j] - M_core[j - 1]

    # --------------------------------------------------------------
    # check whether a new thermal pulse / dredge-up occurred
    # --------------------------------------------------------------

    if TP_count[j] > TP_count[j - 1]:

        tp = TP_count[j]

        # add the newly dredged-up material to this TP's tracer
        tracer[tp] += M_DUP[tp]

    # --------------------------------------------------------------
    # composition of the envelope
    # --------------------------------------------------------------

    # fraction of the envelope belonging to each TP
    fraction = tracer / M_env[j - 1]

    # --------------------------------------------------------------
    # remove the corresponding fraction through each channel
    # --------------------------------------------------------------

    dm_core_i = fraction * dm_core
    dm_wind_i = fraction * dm_wind
    dm_transfer_i = fraction * dm_transfer

    # update the tracer masses
    tracer -= dm_core_i
    tracer -= dm_wind_i
    tracer -= dm_transfer_i

    # accumulate where the material went
    core_lost += dm_core_i
    wind_lost += dm_wind_i
    accreted += dm_transfer_i

    # --------------------------------------------------------------
    # save history
    # --------------------------------------------------------------

    tracer_history[:, j] = tracer
    core_history[:, j] = core_lost
    wind_history[:, j] = wind_lost
    accreted_history[:, j] = accreted
