import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.style import context
import sys

sys.path.insert(1, "/home/koen/LaTeX-setup/python-files/")
from plot_size import set_size

column = 312.98032
full = 483.69684
plt.style.use("default")
plt.style.use("tex rm")

sys.path.insert(1, "/home/koen/master-internship/")
from scripts.general_utils.cplot import cplot
from scripts.general_utils.cache import get_star
from scripts.general_utils.m_dup import compute_m_DUP

plt.cplot = cplot

sys.path.insert(1, "/home/koen/master-internship/")
MASTER = "/home/koen/master-internship/mesa-models/"

import mesa_reader as mr
from scripts.general_utils.mesa_grid_2 import MesaGrid

grid = MesaGrid(f"{MASTER}grid-masses-2026-08-14")
grid2 = MesaGrid(f"{MASTER}grid-masses-2-2026-08-16")

grid.merge(grid2)

# %%

qs = np.arange(0.05, 1.05, 0.05)
rs = np.arange(100, 1260, 10)
# size calculation

qs2 = np.linspace(0.4, 0.7, 4)
qs = [0.4000, 0.4293, 0.6356, 0.6511, 0.7000]
ms = [3, 2.6, 2.2, 1.8]

qqs, mms = np.meshgrid(qs, ms)
qqs2, mms2 = np.meshgrid(qs2, ms)

plt.pcolormesh(qqs, mms, qqs * mms, cmap="viridis")
plt.show()


# %%


masses = qqs * mms
masses2 = qqs2 * mms2
masses = masses.flatten()
masses2 = masses2.flatten()
masses.sort()
masses2.sort()
# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column, height=0.3), constrained_layout=True
)


print(d)

plt.scatter(masses[::2], masses[::2] * 0 + 0.05, s=1.5, marker="o", color="k")
plt.scatter(masses[1::2], masses[1::2] * 0 - 0.05, s=1.5, marker="o", color="k")
plt.scatter(masses2[::2], masses2[::2] * 0 + 1.05, s=1.5, marker="o", color="k")
plt.scatter(masses2[1::2], masses2[1::2] * 0 + 0.95, s=1.5, marker="o", color="k")
# plt.scatter(mild["[Fe/H]"], mild["[Fe/H]"] * 0 + 1, s=1.5, marker="o", color="k")
# plt.scatter(strong["[Fe/H]"], strong["[Fe/H]"] * 0 + 2, s=1.5, marker="o", color="k")

axs.spines[["right", "top", "left"]].set_visible(False)
axs.tick_params(axis="y", which="both", length=0)
plt.xlim(0.7, 2.1)
plt.xticks([0.7, 1, 1.25, 1.5, 1.75, 2.1])

plt.xlabel("[Fe/H]")
labels = ["\\textit{un}equal $q$ spacing", "equal $q$ spacing"]
plt.yticks([0, 1], labels)
plt.ylim(-0.5, 1.5)
plt.savefig("/home/koen/LaTeX-setup/plots/w24-scatter.pgf", format="pgf")
plt.show()
plt.close()


# %%

print(np.linspace(500, 1200, 8))


# %%

8 * 4 * 5
# %%

import numpy as np
from scipy.optimize import differential_evolution

donor_masses = np.array([3.0, 2.6, 2.2, 1.8])


def accretor_masses(q):
    """Return all initial accretor masses for a set of q values."""
    return np.sort(np.outer(q, donor_masses).ravel())


def objective(q_interior):
    """Variance of the spacings between sorted accretor masses."""
    q = np.r_[0.4, np.sort(q_interior), 0.7]

    masses = accretor_masses(q)
    spacings = np.diff(masses)

    return np.var(spacings)


def optimize_q(n):
    """
    Find n q values between 0.4 and 0.7.

    q=0.4 and q=0.7 are always included.
    """

    if n < 2:
        raise ValueError("n must be at least 2")

    if n == 2:
        return np.array([0.4, 0.7])

    result = differential_evolution(
        objective,
        bounds=[(0.4, 0.7)] * (n - 2),
        tol=1e-10,
        polish=True,
        seed=42,
    )

    return np.r_[
        0.4,
        np.sort(result.x),
        0.7,
    ]


# example
n = 5

q = optimize_q(n)

print("q values:")
print(q)

masses = accretor_masses(q)

print("\naccretor masses:")
print(masses)

print("\nspacings:")
print(np.diff(masses))

print("\nvariance:")
print(np.var(np.diff(masses)))
# %%
import numpy as np
from scipy.optimize import differential_evolution

donor_masses = np.array([3.0, 2.6, 2.2, 1.8])

q_min = 0.4
q_max = 0.7


def min_mass_separation(q_interior):
    """
    Return the minimum separation between any two initial
    accretor masses generated by the q values.
    """

    q = np.r_[q_min, np.sort(q_interior), q_max]

    # all combinations of q and donor mass
    accretor_masses = np.outer(q, donor_masses).ravel()

    # sort them so consecutive differences give the spacings
    accretor_masses.sort()

    return np.min(np.diff(accretor_masses))


q_min_separation = 0.01


def objective(q_interior):
    q = np.r_[q_min, np.sort(q_interior), q_max]

    if np.min(np.diff(q)) < q_min_separation:
        return 1e3

    accretor_masses = np.outer(q, donor_masses).ravel()
    accretor_masses.sort()

    return -np.min(np.diff(accretor_masses))


def optimize_q(n, seed=42):
    """
    Find n q values between q_min and q_max that maximize
    the minimum separation between all resulting accretor masses.

    The endpoints q_min and q_max are always included.
    """

    if n < 2:
        raise ValueError("n must be at least 2")

    if n == 2:
        return np.array([q_min, q_max])

    result = differential_evolution(
        objective,
        bounds=[(q_min, q_max)] * (n - 2),
        seed=seed,
        polish=True,
        tol=1e-10,
        workers=1,
    )

    q = np.r_[
        q_min,
        np.sort(result.x),
        q_max,
    ]

    return q


# %%
n = 25

q = optimize_q(n)

print(q)
print("minimum separation:", min_mass_separation(q[1:-1]))

# %%
qs = np.arange(0.05, 1.05, 0.05)
rs = np.arange(100, 1260, 10)

from pathlib import Path
import pickle
from matplotlib.collections import LineCollection
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Rectangle

DATA_DIR = Path("scripts/w23")


# helpers


def load_mass_data(mass):
    """Load all W23 grid data for a given TP-AGB mass."""

    names = [
        "possible",
        "eps_max",
        "eps_min",
        "co",
        "dup",
        "min_mass",
        "max_mass",
        "wind_accretion",
    ]

    for fmt in [f"{mass}", f"{mass:.1f}"]:
        try:
            data = {}

            for name in names:
                path = DATA_DIR / f"const_mass_{name}_{fmt}_small.pkl"

                with open(path, "rb") as f:
                    data[name] = pickle.load(f)

            return data

        except FileNotFoundError:
            continue

    raise FileNotFoundError(f"could not find data for mass {mass}")


def plot_panel(ax, co_matrix, eps_matrix, x, y, norm, cmap):
    """Plot one CO-ratio / epsilon-region panel."""

    ax.pcolormesh(
        x,
        y,
        co_matrix.T,
        shading="nearest",
        cmap=cmap,
        norm=norm,
        rasterized=True,
    )

    draw_region_boundaries(
        ax,
        eps_matrix.T,
        x,
        y,
        colors={
            (0, 0.5): "magenta",
            (0.5, 1): "black",
            (0, 1): "lime",
        },
    )

    ax.contourf(
        x,
        y,
        eps_matrix.T,
        colors="none",
        hatches=["||", None, None, None],
        corner_mask=False,
        rasterized=True,
    )


def plot_by_mass(
    data, variable, masses, rs, qs, norm, cmap, figsize=full, figheight=1.8, ncols=3
):
    ncols = ncols
    nrows = int(np.ceil(len(masses) / ncols))

    fig, axs = plt.subplots(
        nrows,
        ncols,
        sharex=True,
        sharey=True,
        figsize=set_size(figsize, height=figheight),
        constrained_layout=True,
    )

    axs = np.atleast_1d(axs).flatten()

    for ax, mass in zip(axs, masses):
        d = data[mass]

        plot_panel(
            ax,
            d[variable],
            d["possible"],
            rs,
            qs,
            norm,
            cmap,
        )

        ax.set_title(f"$M_{{\\rm TPAGB}} = {mass:.1f}$")

    for ax in axs[len(masses) :]:
        ax.axis("off")

    return fig, axs


def get_q_slice(data, variable, masses, q_index):
    """Return CO and epsilon grids for a fixed q."""

    co = np.array([data[mass][variable][:, q_index] for mass in masses]).T

    eps = np.array([data[mass]["possible"][:, q_index] for mass in masses]).T

    return co, eps


def plot_by_q(
    data,
    variable,
    masses,
    qs,
    rs,
    norm,
    cmap,
    figsize=full,
    figheight=1.8,
    ncols=3,
    q_index_offset=0,
):
    ncols = ncols
    nrows = int(np.ceil(len(qs) / ncols))

    fig, axs = plt.subplots(
        nrows,
        ncols,
        sharex=True,
        sharey=True,
        figsize=set_size(figsize, height=figheight),
        constrained_layout=True,
    )

    axs = np.atleast_1d(axs).flatten()

    for ax, q_index, q in zip(axs, range(len(qs)), qs):

        co, eps = get_q_slice(data, variable, masses, q_index + q_index_offset)

        plot_panel(
            ax,
            co,
            eps,
            rs,
            masses,
            norm,
            cmap,
        )

        ax.set_title(f"$q = {q:.2f}$")

    for ax in axs[len(qs) :]:
        ax.axis("off")

    return fig, axs


def add_colorbar(fig, ax, norm, cmap, label, aspect=20):
    sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])

    cbar = plt.colorbar(
        sm, ax=ax, orientation="horizontal", location="top", aspect=aspect
    )
    cbar.ax.set_xscale("linear")

    cbar.set_label(label)

    return cbar


def draw_region_boundaries(
    ax,
    region,
    x,
    y,
    colors=None,
    linewidth=2,
):
    """
    Draw blocky boundaries between discrete regions.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    region : 2D ndarray
        Region labels (e.g. 0, 0.5, 1).
        Shape must match the pcolormesh array.
    x, y : 1D arrays
        Grid coordinates used by pcolormesh.
    colors : dict, optional
        Dictionary mapping region pairs to colors.
        Example:
        {
            (0, 0.5): "red",
            (0.5, 1): "blue",
            (0, 1): "green",
        }
    linewidth : float
        Line width.
    """

    if colors is None:
        colors = {
            (0, 0.5): "red",
            (0.5, 1): "blue",
            (0, 1): "black",
        }

    segments = []
    segment_colors = []

    ny, nx = region.shape

    # vertical boundaries
    for j in range(ny):
        for i in range(nx - 1):
            a = region[j, i]
            b = region[j, i + 1]

            if a != b:
                pair = tuple(sorted((a, b)))
                if pair in colors:
                    segments.append(
                        [
                            (0.5 * (x[i] + x[i + 1]), y[j] - 0.5 * (y[1] - y[0])),
                            (0.5 * (x[i] + x[i + 1]), y[j] + 0.5 * (y[1] - y[0])),
                        ]
                    )
                    segment_colors.append(colors[pair])

    # horizontal boundaries
    for j in range(ny - 1):
        for i in range(nx):
            a = region[j, i]
            b = region[j + 1, i]

            if a != b:
                pair = tuple(sorted((a, b)))
                if pair in colors:
                    segments.append(
                        [
                            (x[i] - 0.5 * (x[1] - x[0]), 0.5 * (y[j] + y[j + 1])),
                            (x[i] + 0.5 * (x[1] - x[0]), 0.5 * (y[j] + y[j + 1])),
                        ]
                    )
                    segment_colors.append(colors[pair])

    lc = LineCollection(
        segments,
        colors=segment_colors,
        linewidths=linewidth,
        capstyle="butt",
        joinstyle="miter",
        rasterized=True,
        label="test",
    )

    ax.add_collection(lc)

    return lc


# %%
variable = "dup"

# loading data
masses = np.arange(1.0, 3.05, 0.1)
qs = np.arange(0.40, 0.75, 0.05)
rs = np.arange(100, 1260, 10)
data = {m: load_mass_data(m) for m in masses}

# color normalisation
minn = np.min([np.nanmin(d[variable]) for d in data.values()])
maxx = np.max([np.nanmax(d[variable]) for d in data.values()])

# norm = TwoSlopeNorm(vcenter=1, vmin=minn, vmax=maxx)
norm = plt.Normalize(minn, maxx)
cmap = plt.cm.viridis

fig, axs = plot_by_q(
    data,
    variable,
    masses,
    qs,
    rs,
    norm,
    cmap,
    ncols=2,
    q_index_offset=7,
    figsize=column,
)

false_array_1 = np.ones((len(masses), 41))
false_array_2 = np.ones((8, len(rs)))
false_array_3 = np.ones((len(masses), 6))

for ax in axs:
    if ax == axs[-1]:
        continue
    ax.set_xlim(ax.get_xlim())
    ax.set_ylim(ax.get_ylim())
    ax.plot([500, 500, 1200, 1200], [3, 1.8, 1.8, 3.1], c="r", linewidth=2)
    ax.contourf(
        rs[0:41],
        masses,
        false_array_1,
        shading="nearest",
        colors="none",
        hatches=["--", None, None, None],
        corner_mask=False,
        rasterized=True,
    )
    ax.contourf(
        rs,
        masses[0:8],
        false_array_2,
        shading="nearest",
        colors="none",
        hatches=["--", None, None, None],
        corner_mask=False,
        rasterized=True,
    )
    ax.contourf(
        rs[-6:],
        masses,
        false_array_3,
        shading="nearest",
        colors="none",
        hatches=["--", None, None, None],
        corner_mask=False,
        rasterized=True,
    )

# for ax in axs:
# ax.set_xlim(500, 1200)
#     ax.set_ylim(1.8, 3)

custom_lines = [
    Line2D([0], [0], color="magenta", lw=2),
    Line2D([0], [0], color="black", lw=2),
    Line2D([0], [0], color="lime", lw=2),
    Line2D([0], [0], color="red", lw=2),
    Rectangle((0, 0), 2, 2, fill=False, hatch="|||"),
    Line2D([0], [0], color="white", lw=2),
    Line2D([0], [0], color="white", lw=2),
    Line2D([0], [0], color="white", lw=2),
]

fig.supxlabel(r"Initial Roche lobe radius ($R_\odot$)", fontsize=10)
fig.supylabel(r"TPAGB mass ($M_\odot$)", fontsize=10)

fig.legend(
    custom_lines,
    [
        "Border between wind\nregime with possible and\nimpossible final masses",
        "Border between RLOF\nand wind only regime",
        "Border between RLOF\nregime with possible and\nimpossible final masses",
        "Border between possible and\nimpossible MESA models",
        "Impossible region",
        "",
        "",
        "",
    ],
    loc="lower right",
    ncols=1,
    borderpad=0,
    borderaxespad=0,
    # draggable=True,
    frameon=False,
)

fig.supylabel("Initial mass ratio ($q$)", fontsize=10)
fig.supxlabel("Initial Roche lobe radius ($R_\odot$)", fontsize=10)

add_colorbar(
    fig,
    axs[1:3],
    norm,
    cmap,
    label=r"$M_\textrm{DUP}$ at end of \texttt{evolve.py}",
    aspect=35,
)

plt.savefig("/home/koen/LaTeX-setup/plots/w24-mspace-dup.pgf", format="pgf")
plt.show()


# %%

sys.path.insert(1, "/home/koen/master-internship/")
MASTER = "/home/koen/master-internship/mesa-models/"
from scripts.general_utils.cplot import cplot

plt.cplot = cplot
import mesa_reader as mr
from scripts.general_utils.mesa_grid_2 import MesaGrid

# %%

grid = MesaGrid(f"{MASTER}epsilon-grid")

# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

markers = ["*", "^", "s"]

norm = plt.Normalize(0, 1)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for d in grid.axes["delta"]:
    labels = []
    for i, eps in enumerate(grid.settings["eps"]):
        print(eps)

        dt_mins = []
        env_mass = []
        for model in grid.filter(f_delta=d, eps=eps):
            dt_mins.append(np.min(model.log_dt))
            env_mass.append(model.envelope_mass[-1])
        l = plt.scatter(
            dt_mins,
            env_mass,
            color=cmap(norm(d)),
            label=f"$\\varepsilon = {eps:.2f}$",
            marker=markers[i],
            s=10,
        )
        labels.append(l)


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

fig.legend(loc="outside upper center", ncols=4, handles=labels)
cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$\delta / (1-\varepsilon)$")

axs.spines[["right", "top"]].set_visible(False)
plt.yscale("log")
plt.xlabel(r"$\textrm{min}(\log(\Delta t / \textrm{yr})$")
plt.ylabel("Envelope mass at end of evolution ($M_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-minlogt.pgf", format="pgf")
plt.show()
plt.close()

# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

markers = ["*", "^", "s"]

norm = plt.Normalize(0, 1)
cmap = plt.cm.viridis
# color = cmap(norm(x))


min_model = grid.models[np.argmin([model.envelope_mass[-1] for model in grid.models])]
for d in grid.axes["delta"]:
    labels = []
    for i, eps in enumerate(grid.settings["eps"]):

        dt_mins = []
        env_mass = []
        for model in grid.filter(f_delta=d, eps=eps):
            dt_mins.append(model.R[-1])
            env_mass.append(model.envelope_mass[-1])
        l = plt.scatter(
            dt_mins,
            env_mass,
            color=cmap(norm(d)),
            label=f"$\\varepsilon = {eps:.2f}$",
            marker=markers[i],
            s=10,
        )
        labels.append(l)

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

fig.legend(loc="outside upper center", ncols=4, handles=labels)
cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$\delta / (1-\varepsilon)$")

axs.spines[["right", "top"]].set_visible(False)
plt.yscale("log")
plt.xlabel(r"$\textrm{min}(\log(\Delta t / \textrm{yr})$")
plt.ylabel(r"Envelope mass at end of evolution ($M_\odot$)")
# plt.savefig("/home/koen/LaTeX-setup/plots/w24-minlogt.pgf", format="pgf")
plt.show()
plt.close()


# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

print(min_model.bulk_names)
for d in grid.axes["delta"]:
    labels = []
    for model in grid.filter(f_delta=d, eps=grid.settings["eps"][0]):
        lc = plt.cplot(
            model.log_Teff, model.log_L, c=model.R / model.rl_1, cmap="viridis"
        )

plt.colorbar(lc)
axs.invert_xaxis()

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("")
plt.ylabel("")
plt.savefig("/home/koen/LaTeX-setup/plots/.pgf", format="pgf")
plt.show()
plt.close()
# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

markers = ["*", "^", "s"]

norm = plt.Normalize(0, 1)
cmap = plt.cm.viridis
# color = cmap(norm(x))


min_model = grid.models[np.argmin([model.envelope_mass[-1] for model in grid.models])]
for d in grid.axes["delta"]:
    labels = []
    for i, eps in enumerate(grid.settings["eps"]):

        dt_mins = []
        env_mass = []
        for model in grid.filter(f_delta=d, eps=eps):
            dt_mins.append(np.max(model.R / model.rl_1))
            env_mass.append(model.star_2_mass[-1] - model.star_2_mass[0])
        l = plt.scatter(
            env_mass,
            dt_mins,
            color=cmap(norm(d)),
            label=f"$\\varepsilon = {eps:.2f}$",
            marker=markers[i],
            s=10,
        )
        labels.append(l)

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

fig.legend(loc="outside upper center", ncols=4, handles=labels)
cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$\delta / (1-\varepsilon)$")

axs.spines[["right", "top"]].set_visible(False)
# plt.yscale("log")
plt.xlabel(r"$\textrm{min}(\log(\Delta t / \textrm{yr})$")
plt.ylabel(r"Envelope mass at end of evolution ($M_\odot$)")
# plt.savefig("/home/koen/LaTeX-setup/plots/w24-minlogt.pgf", format="pgf")
plt.show()
plt.close()


# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

print(min_model.bulk_names)
for d in grid.axes["delta"]:
    labels = []
    for model in grid.filter(f_delta=d, eps=grid.settings["eps"][0]):
        lc = plt.cplot(
            model.envelope_mass, model.R, c=model.R / model.rl_1, cmap="viridis"
        )

plt.colorbar(lc)
# axs.invert_xaxis()

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("")
plt.ylabel("")
# plt.savefig("/home/koen/LaTeX-setup/plots/.pgf", format="pgf")
plt.show()
plt.close()
# %%


def find_CO(r):
    if r.period_days[-1] < 50:
        return np.nan

    try:
        ind = np.argwhere(r.rl_1 < r.R)[0][0]
        return r.period_days[-1]
    except:
        return np.nan


fig, axs = plt.subplots(
    1, 1, sharey=True, figsize=set_size(full, height=0.5), constrained_layout=True
)

minn = 1e99
maxx = -1e-99


R, q, ratio = grid.array(
    find_CO,
    x="R",
    y="q",
)
minn = np.nanmin(ratio) if np.nanmin(ratio) < minn else minn
maxx = np.nanmax(ratio) if np.nanmax(ratio) > maxx else maxx


c = plt.pcolormesh(
    R,
    q,
    ratio.T,
    shading="auto",
    cmap="viridis",
    vmin=minn,
    vmax=maxx,
    rasterized=True,
)

plt.colorbar(
    c,
    ax=axs,
    orientation="horizontal",
    location="top",
    aspect=50,
    label="Observed CO-ratio (no mixing in barium star)",
)
plt.xlabel("")
plt.ylabel("")
# plt.savefig("/home/koen/LaTeX-setup/plots/w22-eps-hist-CO-no-mixing.pgf", format="pgf")
plt.show()
plt.close()
# %%

star = get_star(m=2.6)

# plt.plot(star.age, star.log_R)
# print(star.m_DUP_time)

for tp in np.unique(np.asarray(star.TP_count)[star.ntpagb :]):
    plt.plot(star.age, star.m_DUP_time[tp])
plt.plot(star.age, star.TP_count / 10000)
plt.plot(star.age, star.m_DUP_time[0])
plt.show()
# %%


TP_count = np.asarray(star.TP_count)[star.ntpagb :]
print(TP_count)
# %%

for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    plt.plot(star.age, star.m_DUP_time[0])
plt.show()
# %%


def mass_envelope_dredge_up_something(star):

    m_DUP_left = {}
    m_DUP_left[0] = 0 * star.m_DUP_time[0]
    for tp in np.unique(np.asarray(star.TP_count)[star.ntpagb :]):
        try:
            arg = np.argwhere(star.m_DUP_time[tp] > 0)[0][0]
            ref = star.m_env[arg]
            m_DUP_left[tp] = star.m_DUP_time[tp] * star.m_env / ref
            m_DUP_left[0] += star.m_DUP_time[tp] * star.m_env / ref
        except:
            m_DUP_left[tp] = star.m_DUP_time[tp]
    return m_DUP_left


# %%
norm = plt.Normalize(1, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    m_DUP_left = mass_envelope_dredge_up_something(star)

    plt.plot(
        star.age[star.ntpagb :] - star.age[star.ntpagb],
        m_DUP_left[0][star.ntpagb :],
        c=cmap(norm(m)),
    )


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"label")

plt.show()


# %%
norm = plt.Normalize(1, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    m_DUP_left = mass_envelope_dredge_up_something(star)

    plt.plot(
        star.m_env[star.ntpagb :],
        m_DUP_left[0][star.ntpagb :] / star.m_env[star.ntpagb :],
        c=cmap(norm(m)),
    )


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"label")

plt.show()


# %%
from matplotlib import ticker

norm = plt.Normalize(1, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    m_DUP_left = mass_envelope_dredge_up_something(star)

    plt.plot(
        star.age[star.ntpagb :] - star.age[star.ntpagb],
        star.m_DUP_time[0][star.ntpagb :],
        c=cmap(norm(m)),
    )


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"label")

# plt.gca().yaxis.set_major_formatter(ticker.PercentFormatter(1))
plt.show()


# %%

from matplotlib import ticker

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(1, np.nanmax(star.TP_count))
cmap = plt.cm.plasma
# color = cmap(norm(x))


m = 2.5
star = get_star(m=2.5)

for i, tp in enumerate(np.unique(star.TP_count[star.ntpagb :])):

    plt.plot(
        star.age[star.ntpagb :] - star.age[star.ntpagb],
        star.m_DUP_time[tp][star.ntpagb :],
        c=cmap(norm(tp)),
        linewidth=2 if i % 2 == 0 else 0.8,
    )

plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    star.m_DUP_time[0][star.ntpagb :],
    c="C2",
    linewidth=2,
    label="sum of individiual TDU events",
)

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"Thermal pulse count")

plt.yscale("log")

fig.legend(loc="outside upper center")

plt.text(
    0.05, 0.95, f"$M_\\textrm{{TPAGB, i}} = {2.5}\\;M_\\odot$", transform=axs.transAxes
)
plt.ylim(1e-7)

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time since TPAGB (yr)")
plt.ylabel(r"$M_\textrm{DUP}$ ($M_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-TDU-individual.pgf", format="pgf")
plt.show()
plt.close()


# %%

from matplotlib import ticker

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(1, np.nanmax(star.TP_count))
cmap = plt.cm.plasma
# color = cmap(norm(x))


m = 2.5
star = get_star(m=2.5)

m_DUP_left = mass_envelope_dredge_up_something(star)

# for i, tp in enumerate(np.unique(star.TP_count[star.ntpagb:])):
#
#     plt.plot(star.age[star.ntpagb:] - star.age[star.ntpagb], m_DUP_left[tp][star.ntpagb:], c = cmap(norm(tp)), linewidth=2 if i%2==0 else 0.8)

plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    m_DUP_left[0][star.ntpagb :],
    c="C0",
    label="Actual in envelope",
)
plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    star.m_DUP_time[0][star.ntpagb :],
    c="C1",
    label="TDU amount",
    zorder=-1,
)

plt.text(
    0.05, 0.95, f"$M_\\textrm{{TPAGB, i}} = {2.5}\\;M_\\odot$", transform=axs.transAxes
)
sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

# cbar = plt.colorbar(sm, ax=plt.gca())
# cbar.set_label(r"Thermal pulse count")

# plt.yscale("log")

fig.legend(loc="outside upper center", ncols=2)

plt.ylim(1e-7)

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time since TPAGB (yr)")
plt.ylabel(r"$M_\textrm{DUP}$ in enevelope ($M_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-TDU-left.pgf", format="pgf")
plt.show()
plt.close()


# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(1, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))

for m in np.arange(1, 3.05, 0.1):
    star = get_star(m=m)
    m_DUP_left = mass_envelope_dredge_up_something(star)

    plt.plot(
        star.age[star.ntpagb :] - star.age[star.ntpagb],
        m_DUP_left[0][star.ntpagb :],
        c=cmap(norm(m)),
    )

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$M_\textrm{TPAGB, i}$ ($M_\odot$)")

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time since TPAGB (yr)")
plt.ylabel(r"$M_\textrm{DUP}$ in enevelope ($M_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-TDU-diff-masses.pgf", format="pgf")
plt.show()
plt.close()

# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

ms = np.arange(1, 3.05, 0.1)

age = []

for m in ms:
    star = get_star(m=m)
    age.append(star.age[-1] - star.age[star.ntpagb])

plt.plot(ms, age, c="k")
plt.scatter(ms, age, zorder=11, marker=".", c="k")
plt.scatter(ms, age, zorder=10, s=200, marker=".", c="white")

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel(r"Initial TPAGB mass ($M_\odot$)")
plt.ylabel("TPAGB age (yr)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-mass-tpagb-time.pgf", format="pgf")
plt.show()
plt.close()

# %%

from matplotlib import ticker

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(1, np.nanmax(star.TP_count))
cmap = plt.cm.plasma
# color = cmap(norm(x))


m = 2.5
star = get_star(m=2.5)

m_DUP_left = mass_envelope_dredge_up_something(star)

# for i, tp in enumerate(np.unique(star.TP_count[star.ntpagb:])):
#
#     plt.plot(star.age[star.ntpagb:] - star.age[star.ntpagb], m_DUP_left[tp][star.ntpagb:], c = cmap(norm(tp)), linewidth=2 if i%2==0 else 0.8)

plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    star.m_DUP_time[0][star.ntpagb :] - m_DUP_left[0][star.ntpagb :],
    c="C1",
    label="TDU amount",
    zorder=-1,
)

plt.text(
    0.05, 0.95, f"$M_\\textrm{{TPAGB, i}} = {2.5}\\;M_\\odot$", transform=axs.transAxes
)
sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

# cbar = plt.colorbar(sm, ax=plt.gca())
# cbar.set_label(r"Thermal pulse count")

# plt.yscale("log")

fig.legend(loc="outside upper center", ncols=2)

plt.ylim(1e-7)

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time since TPAGB (yr)")
plt.ylabel(r"$M_\textrm{DUP}$ in enevelope ($M_\odot$)")
# plt.savefig("/home/koen/LaTeX-setup/plots/w24-TDU-left.pgf", format="pgf")
plt.show()
plt.close()


# %%

dt = np.diff(star.age)
plt.plot(star.age[star.ntpagb :], star.m_env[star.ntpagb] - star.m_env[star.ntpagb :])
plt.plot(
    star.age[star.ntpagb :], np.cumsum(star.Mdot[star.ntpagb :] * dt[star.ntpagb - 1 :])
)
plt.show()

# %%

plt.plot(star.age[star.ntpagb :], star.m_core[star.ntpagb :])
plt.show()
# %%

print(star.m_core[-1] - star.m_core[star.ntpagb])
# %%

dt = np.diff(star.age)
plt.plot(
    star.age[star.ntpagb :], np.cumsum(star.Mdot[star.ntpagb :] * dt[star.ntpagb - 1 :])
)
plt.plot(star.age[star.ntpagb :], star.m_core[star.ntpagb :] - star.m_core[star.ntpagb])
plt.plot(star.age[star.ntpagb :], star.m_env[star.ntpagb :])
plt.show()


# %%
dt = np.diff(star.age)
dot_m_core = (np.diff(star.m_core) / dt)[star.ntpagb - 1 :]
dot_m_wind = star.Mdot[star.ntpagb :]


# %%

# input arrays from your mesa/model data
time = star.age[star.ntpagb :]
M_env = star.m_env[star.ntpagb :]
M_core = star.m_core[star.ntpagb :]
mdot_transfer = 0 * star.Mdot[star.ntpagb :]
mdot_wind = star.Mdot[star.ntpagb :]

TP_count = star.TP_count[star.ntpagb :]
M_DUP = 0 + star.m_DUP

# ----------------------------------------------------------------------
# storage
# ----------------------------------------------------------------------


n_times = len(time)
n_TP = len(M_DUP)

# mass from each TP currently remaining in the donor envelope
tracer = np.zeros(n_TP)

# cumulative fate of the material from each TP
accreted = np.zeros(n_TP)
wind_lost = np.zeros(n_TP)
core_lost = np.zeros(n_TP)

# optionally store the full history
tracer_history = np.zeros((n_TP, n_times))
accreted_history = np.zeros((n_TP, n_times))
wind_history = np.zeros((n_TP, n_times))
core_history = np.zeros((n_TP, n_times))


# ----------------------------------------------------------------------
# evolve through the stellar track
# ----------------------------------------------------------------------

for j in range(1, n_times):

    dt = time[j] - time[j - 1]

    # mass-loss rates should be positive here
    dm_transfer = mdot_transfer[j] * dt
    dm_wind = mdot_wind[j] * dt

    # core growth
    dm_core = max(M_core[j] - M_core[j - 1], 0)
    # dm_core = M_core[j] - M_core[j - 1]

    # --------------------------------------------------------------
    # check whether a new thermal pulse / dredge-up occurred
    # --------------------------------------------------------------

    if TP_count[j] > TP_count[j - 1]:

        tp = int(TP_count[j])

        # add the newly dredged-up material to this TP's tracer
        try:
            tracer[tp - 1] += M_DUP[tp - 1]
        except:
            pass

    # --------------------------------------------------------------
    # composition of the envelope
    # --------------------------------------------------------------

    # fraction of the envelope belonging to each TP
    fraction = tracer / M_env[j - 1]

    # --------------------------------------------------------------
    # remove the corresponding fraction through each channel
    # --------------------------------------------------------------

    dm_core_i = fraction * dm_core
    dm_wind_i = fraction * dm_wind
    dm_transfer_i = fraction * dm_transfer

    # update the tracer masses
    tracer -= dm_core_i
    tracer -= dm_wind_i
    tracer -= dm_transfer_i

    # accumulate where the material went
    core_lost += dm_core_i
    wind_lost += dm_wind_i
    accreted += dm_transfer_i

    # --------------------------------------------------------------
    # save history
    # --------------------------------------------------------------

    tracer_history[:, j] = tracer
    core_history[:, j] = core_lost
    wind_history[:, j] = wind_lost
    accreted_history[:, j] = accreted
# %%

winds = np.zeros(len(time))
cores = np.zeros(len(time))
traces = np.zeros(len(time))

for wind, core, trace in zip(wind_history, core_history, tracer_history):
    winds += wind
    cores += core
    traces += trace


plt.plot(star.age[star.ntpagb :], traces)
plt.plot(star.age[star.ntpagb :], cores)
plt.plot(star.age[star.ntpagb :], winds)
plt.show()

# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(full, height=0.5), constrained_layout=True
)

winds = np.zeros(len(time))
cores = np.zeros(len(time))
traces = np.zeros(len(time))

for wind, core, trace in zip(wind_history, core_history, tracer_history):
    winds += wind
    cores += core
    traces += trace

    # plt.plot(star.age[star.ntpagb:], trace + wind)

plt.plot(star.age[star.ntpagb :], traces + winds + cores, label="TDU only")
plt.plot(star.age[star.ntpagb :], traces + winds, label="TDU + core growth")
plt.plot(star.age[star.ntpagb :], traces, label="TDU + core growth + mass loss")

fig.legend(loc="outside upper center", ncols=4)

plt.text(
    0.05, 0.95, f"$M_\\textrm{{TPAGB, i}} = {2.5}\\;M_\\odot$", transform=axs.transAxes
)

plt.xlim(6.458e8)

axs.spines[["right", "top"]].set_visible(False)
plt.ylabel(r"Dredged up mass in envelope ($M_\odot$)")
plt.xlabel("Time since TPAGB (yr)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-components-dup.pgf", format="pgf")
plt.show()
plt.close()

# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(full, height=0.5), constrained_layout=True
)

winds = np.zeros(len(time))
cores = np.zeros(len(time))
traces = np.zeros(len(time))

for i, (wind, core, trace) in enumerate(
    zip(wind_history, core_history, tracer_history)
):
    if i != 10:
        continue
    plt.plot(star.age[star.ntpagb :], trace + wind + core)
    plt.plot(star.age[star.ntpagb :], trace + wind)
    plt.plot(star.age[star.ntpagb :], trace)


# plt.plot(star.age[star.ntpagb:], traces)
# plt.plot(star.age[star.ntpagb:], cores)
# plt.plot(star.age[star.ntpagb:], winds)
plt.text(
    0.05,
    0.95,
    f"$M_\\textrm{{TPAGB, i}} = {2.5}\\;M_\\odot$, TDU 10",
    transform=axs.transAxes,
)

axs.spines[["right", "top"]].set_visible(False)
plt.ylabel(r"Dredged up mass in envelope ($M_\odot$)")
plt.xlabel("Time since TPAGB (yr)")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-components-dup-single.pgf", format="pgf")
plt.show()
plt.close()


# %%

sys.path.insert(1, "/home/koen/master-internship/")
MASTER = "/home/koen/master-internship/mesa-models/"

import mesa_reader as mr
from scripts.general_utils.mesa_grid_2 import MesaGrid

grid = MesaGrid(f"{MASTER}grid-masses-2026-08-14")
# %%

norm = plt.Normalize(0.4, 0.7)
cmap = plt.cm.viridis
# color = cmap(norm(x))


count = 0
for model in grid.models:
    if model.env_mass[-1] < 0.01:
        count += 1
        plt.plot(model.age, model.R, c="C9")
        plt.plot(model.age, model.rl_1, c=cmap(norm(model.q[0])))

sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"label")

print(count)
plt.show()
# %%

fig, axs = plt.subplots(
    2, 2, sharex=True, sharey=True, figsize=set_size(full), constrained_layout=True
)

axs = axs.flatten()

for ax in axs:
    ax.spines[["right", "top"]].set_visible(False)
    ax.set_ylim(0.01, 3)
    ax.set_yscale("log")

for ax, m in zip(axs, [1.8, 2.2, 2.6, 3.0]):
    m = np.round(m, 1)
    ax.text(
        0.95,
        0.05,
        f"$M = {m:.1f}\\;M_\\odot$",
        transform=ax.transAxes,
        va="bottom",
        ha="right",
    )
    for model in grid.filter(m=m):
        if m != 1.8:
            if model.env_mass[-1] < 0.01:
                ax.plot(model.rl_1, model.env_mass, c="C2", linewidth=2, zorder=1000)
                ax.plot(model.rl_1, model.env_mass, c="white", linewidth=5, zorder=100)
            else:
                (n,) = ax.plot(
                    model.rl_1, model.env_mass, c="C3", label="Unsuccessful model"
                )
        else:
            if model.env_mass[-1] < 0.01:
                (l,) = ax.plot(
                    model.rl_1, model.env_mass, c="C2", label="Successful model"
                )
            else:
                ax.plot(model.rl_1, model.env_mass, c="C3", linewidth=2, zorder=1000)
                ax.plot(model.rl_1, model.env_mass, c="white", linewidth=5, zorder=100)


fig.legend(handles=[n, l], loc="outside upper center", ncols=2)

fig.supxlabel(r"Roche lobe radius ($R_\odot$)", fontsize=10)
fig.supylabel(r"Envelope mass ($M_\odot$)", fontsize=10)
plt.savefig("/home/koen/LaTeX-setup/plots/w24-grid-1-success.pgf", format="pgf")
plt.show()
plt.close()
# %%

fig, axs = plt.subplots(
    2, 2, sharex=True, sharey=True, figsize=set_size(column), constrained_layout=True
)

axs = axs.flatten()

for ax in axs:
    ax.spines[["right", "top"]].set_visible(False)
    ax.set_ylim(0.01, 3)
    ax.set_yscale("log")

for ax, m in zip(axs, [1.8, 2.2, 2.6, 3.0]):
    print(m)
    for model in grid.filter(m=m):
        if m != 1.8:
            if model.env_mass[-1] < 0.01:
                ax.plot(
                    model.log_Teff,
                    model.env_mass,
                    c="C2",
                    linewidth=2,
                    zorder=1000,
                )
                ax.plot(
                    model.log_Teff,
                    model.env_mass,
                    c="white",
                    linewidth=5,
                    zorder=100,
                )
            else:
                ax.plot(model.log_Teff, model.env_mass, c="C3")
        else:
            if model.env_mass[-1] < 0.01:
                ax.plot(model.log_Teff, model.env_mass, c="C2")
            else:
                ax.plot(
                    model.log_Teff,
                    model.env_mass,
                    c="C3",
                    linewidth=2,
                    zorder=1000,
                )
                ax.plot(
                    model.log_Teff,
                    model.env_mass,
                    c="white",
                    linewidth=5,
                    zorder=100,
                )

axs[0].invert_xaxis()

plt.xlabel("")
plt.ylabel("")
# plt.savefig("/home/koen/LaTeX-setup/plots/.pgf", format="pgf")
plt.show()
plt.close()

# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)


for ax, m in zip([axs], [3.0]):
    print(m)
    for model in grid.filter(m=m):
        if model.env_mass[-1] < 0.01:
            ax.plot(
                model.age,
                model.rl_1,
                c="C2",
                linewidth=2,
                zorder=1000,
            )
            ax.plot(model.age, model.R, c="C2", linewidth=3, alpha=0.5)

        else:
            ax.plot(
                model.age,
                model.rl_1,
                c="C3",
            )
            ax.plot(model.age, model.R, c="C3", linewidth=3, alpha=0.5)

star = get_star(m=m)
plt.plot(star.age[star.ntpagb :], 10 ** star.log_R[star.ntpagb :], c="C9")
axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("")
plt.ylabel("")
plt.savefig("/home/koen/LaTeX-setup/plots/.pgf", format="pgf")
plt.show()
plt.close()
# %%
model.bulk_names
# %%
plt.plot(model.age, model.period_days)
plt.plot(model.age, model.envelope_mass)

plt.show()
# %%

m3broken = get_star(
    full_path="/home/koen/master-internship/mesa-models/single-stars/z0.00557/first-try/M2.6/",
    m=2.6,
)

# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(full, height=0.5), constrained_layout=True
)

markers = ["o", "^", "s", "*"]

ls = []
for i, m in enumerate([1.8, 2.2, 2.6, 3.0]):
    print(m)
    for model in grid.filter(m=m):
        l = axs.scatter(
            model.envelope_mass[-1],
            model.R[-1] / model.rl_1[-1],
            c=f"C{i}",
            marker=markers[i],
            label=f"$M={m:.1f}\\;M_\\odot$",
            s=15,
        )

    for model in grid2.filter(m=m):
        l = axs.scatter(
            model.envelope_mass[-1],
            model.R[-1] / model.rl_1[-1],
            c=f"C{i}",
            marker=markers[i],
            label=f"$M={m:.1f}\\;M_\\odot$",
            s=15,
        )

    mbroken = get_star(
        full_path=f"/home/koen/master-internship/mesa-models/single-stars/z0.00557/first-try/M{m}/",
        m=m,
    )
    plt.axvline(mbroken.m_env[-1], c=f"C{i}", linewidth=0.75, zorder=-10)
    ls.append(l)

plt.legend(handles=ls, loc="upper left")

plt.axhline(1, c="C9", linewidth=0.75, zorder=-10)
plt.xscale("log")
plt.ylim(0, 3)

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("$M_\\textrm{env}$ ($M_\odot$)")
plt.ylabel("last $R_\\textrm{star} /R_\\textrm{RL}$")

plt.savefig("/home/koen/LaTeX-setup/plots/w24-grid-scatter.pgf", format="pgf")
plt.show()
# %%


def find_m_env(r):
    try:
        r.period_days[-1]
    except IndexError:
        return np.nan

    return np.log10(r.envelope_mass[-1])


fig, axs = plt.subplots(
    1, 3, sharey=True, figsize=set_size(full, height=0.5), constrained_layout=True
)

minn = 1e99
maxx = -1e-99

for i, ax in enumerate(axs):

    R, q, ratio = grid.array(find_m_env, x="R", y="q")
    minn = np.nanmin(ratio) if np.nanmin(ratio) < minn else minn
    maxx = np.nanmax(ratio) if np.nanmax(ratio) > maxx else maxx

print(minn, maxx)

ms = [1.8, 2.2, 2.6, 3.0]

for i, ax in enumerate(axs):

    R, q, ratio = grid.array(find_m_env, x="R", y="q", m=ms[i])

    c = axs[i].pcolormesh(
        R,
        q,
        ratio.T,
        shading="auto",
        cmap="viridis",
        vmin=-2,
        vmax=maxx,
        rasterized=True,
    )


axs[1].set_xlabel(r"$\delta$ ($1 - \beta$)")
axs[0].set_ylabel("$q$ ($M_\\textrm{a} / M_\\textrm{d}$)")
plt.colorbar(
    c,
    ax=axs,
    orientation="horizontal",
    location="top",
    aspect=50,
    label="Observed CO-ratio (no mixing in barium star)",
)
plt.xlabel("")
plt.ylabel("")
# plt.savefig("/home/koen/LaTeX-setup/plots/w22-eps-hist-CO-no-mixing.pgf", format="pgf")
plt.show()
plt.close()


# %%
fig, axs = plt.subplots(
    1, 1, sharey=True, figsize=set_size(full, height=0.5), constrained_layout=True
)


norm = plt.Normalize(1.4, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))

for m in np.arange(1.4, 3.01, 0.1):
    m = np.round(m, 1)
    star = get_star(m=m)
    if m in [1.8, 2.2, 2.6, 3]:
        plt.plot(
            star.m_env[star.ntpagb :],
            10 ** star.log_R[star.ntpagb :],
            color=cmap(norm(m)),
            linewidth=3,
            zorder=1000,
        )
        plt.plot(
            star.m_env[star.ntpagb :],
            10 ** star.log_R[star.ntpagb :],
            color="w",
            linewidth=6,
            zorder=100,
        )
    else:
        plt.plot(
            star.m_env[star.ntpagb :],
            10 ** star.log_R[star.ntpagb :],
            color=cmap(norm(m)),
            linewidth=0.75,
        )
sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"Initial TPAGB mass ($M_\odot$)")

plt.xscale("log")
plt.yscale("log")

plt.ylabel(r"Radius ($R_\odot$)")
plt.xlabel(r"Envelope mass ($M_\odot$)")

axs.spines[["right", "top"]].set_visible(False)
plt.xlim(10 ** (-2.1), 10 ** (-0.2))
plt.ylim(10 ** (2), 1500)
plt.axvline(0.1, c="C9", linewidth=0.75, zorder=-1)
plt.savefig("/home/koen/LaTeX-setup/plots/w24-single-star-pulsations.pgf", format="pgf")
plt.show()
# %%

fig, axs = plt.subplots(
    9, 1, sharex=True, figsize=set_size(full, height=1), constrained_layout=True
)
norm = plt.Normalize(1.4, 3)
cmap = plt.cm.viridis
# color = cmap(norm(x))

for i, m in enumerate(np.arange(1.4, 3.01, 0.1)[::-1]):
    m = np.round(m, 1)
    star = get_star(m=m)
    axs[i // 2].plot(
        star.m_env[star.ntpagb + 1 :],
        np.diff(10 ** star.log_R[star.ntpagb :]) / np.diff(star.age[star.ntpagb :]),
        color=cmap(norm(m)),
        linewidth=0.75,
    )

    if m == 1.4:
        axs[i // 2].text(
            0.95,
            0.95,
            f"$M = {m:.1f}\\;M_\\odot$",
            va="top",
            ha="right",
            transform=axs[i // 2].transAxes,
        )
    elif i % 2 == 0:
        axs[i // 2].text(
            0.95,
            0.95,
            f"$M = {m:.1f}, {m-0.1:.1f}\\;M_\\odot$",
            va="top",
            ha="right",
            transform=axs[i // 2].transAxes,
        )
sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=axs, aspect=50)
cbar.set_label(r"Initial TPAGB mass ($M_\odot$)")

plt.xscale("log")
# plt.yscale("log")

fig.supylabel(r"$\textrm{d}R / \textrm{d}t$", fontsize=10)
fig.supxlabel(r"Envelope mass ($M_\odot$)", fontsize=10)

for ax in axs:
    ax.spines[["right", "top"]].set_visible(False)
    ax.axvline(0.1, c="C9", linewidth=0.75, zorder=-1)
plt.xlim(10 ** (-2.1), 10 ** (-0.2))
# plt.ylim(10**(2), 1500)
plt.savefig(
    "/home/koen/LaTeX-setup/plots/w24-single-star-pulsations-delta.pgf", format="pgf"
)
plt.show()

# %%

print(model.bulk_names)
plt.plot(model.age, np.log10(model.min_T))
plt.show()

# %%


count = 0

fig, axs = plt.subplots(
    2, 2, sharex=True, sharey=True, figsize=set_size(column), constrained_layout=True
)

axs = axs.flatten()

for ax in axs:
    ax.spines[["right", "top"]].set_visible(False)
    ax.set_ylim(0.01, 3)
    ax.set_yscale("log")

for ax, m in zip(axs, [1.8, 2.2, 2.6, 3.0]):
    print(m)

    for model in grid.filter(m=m):
        if m != 1.8:
            if model.env_mass[-1] < 0.01:
                count += 1
                ax.plot(
                    model.rl_1,
                    model.env_mass,
                    c="C2",
                    linewidth=2,
                    zorder=1000,
                )
                ax.plot(
                    model.rl_1,
                    model.env_mass,
                    c="white",
                    linewidth=5,
                    zorder=100,
                )
            else:
                ax.plot(model.rl_1, model.env_mass, c="C3")
        else:
            if model.env_mass[-1] < 0.01:
                ax.plot(model.rl_1, model.env_mass, c="C2")
                count += 1
            else:
                ax.plot(
                    model.rl_1,
                    model.env_mass,
                    c="C3",
                    linewidth=2,
                    zorder=1000,
                )
                ax.plot(
                    model.rl_1,
                    model.env_mass,
                    c="white",
                    linewidth=5,
                    zorder=100,
                )


# axs[0].invert_xaxis()
print(count)
print(len(grid.models) + len(grid2.models))

plt.xlabel("")
plt.ylabel("")
# plt.savefig("/home/koen/LaTeX-setup/plots/.pgf", format="pgf")
plt.show()
plt.close()


# %%


def find_m_env(r):
    try:
        r.period_days[-1]
    except IndexError:
        return np.nan

    return np.log10(r.envelope_mass[-1])


fig, axs = plt.subplots(
    2,
    2,
    sharey=True,
    sharex=True,
    figsize=set_size(full, height=1),
    constrained_layout=True,
)

minn = 1e99
maxx = -1e99

axs = axs.flatten()

R, q, ratio = grid.array(find_m_env, x="R", y="q")

minn = np.nanmin(ratio) if np.nanmin(ratio) < minn else minn
maxx = np.nanmax(ratio) if np.nanmax(ratio) > maxx else maxx

ms = [1.8, 2.2, 2.6, 3.0]

for i, ax in enumerate(axs):

    ax.set_title(f"$M_\\textrm{{TPAGB}} = {ms[i]:.1f}\\;M_\\odot$")
    R, q, ratio = grid.array(find_m_env, x="R", y="q", m=ms[i])

    c = axs[i].pcolormesh(
        R,
        q,
        ratio.T,
        shading="auto",
        cmap="viridis",
        vmin=-2,
        vmax=maxx,
        rasterized=True,
    )


fig.supxlabel(r"Roche lobe radius ($R_\odot$)", fontsize=10)
fig.supylabel("$q$ ($M_\\textrm{a} / M_\\textrm{d}$)", fontsize=10)
plt.colorbar(
    c,
    ax=axs,
    orientation="horizontal",
    location="top",
    aspect=50,
    label=r"Final envelope mass ($M_\odot$)",
    extend="min",
)
plt.yticks(
    [0.7, 0.66, 0.63, 0.6, 0.5, 0.44, 0.4][::-1], [f"{q:.2f}" for q in grid.axes["q"]]
)

plt.savefig("/home/koen/LaTeX-setup/plots/w24-grid-envelope-mass.pgf", format="pgf")
plt.show()
plt.close()


# %%


def z(r):
    try:
        r.period_days[-1]
    except IndexError:
        return np.nan

    if r.envelope_mass[-1] > 1e-2:
        return np.nan

    return r.period_days[-1]


fig, axs = plt.subplots(
    1,
    1,
    sharey=True,
    sharex=True,
    figsize=set_size(column),
    constrained_layout=True,
)


minn = 1e99
maxx = -1e99


R, q, ratio = grid.array(z, x="R", y="q")

minn = np.nanmin(ratio) if np.nanmin(ratio) < minn else minn
maxx = np.nanmax(ratio) if np.nanmax(ratio) > maxx else maxx

ms = [1.8]

for i, ax in enumerate([axs]):

    ax.set_title(f"$M_\\textrm{{TPAGB}} = {ms[i]:.1f}\\;M_\\odot$")
    R, q, ratio = grid.array(z, x="R", y="q", m=ms[i])

    c = axs.pcolormesh(
        R,
        q,
        ratio.T,
        shading="auto",
        cmap="viridis",
        vmin=minn,
        vmax=maxx,
        rasterized=True,
    )


fig.supxlabel(r"Roche lobe radius ($R_\odot$)", fontsize=10)
fig.supylabel("$q$ ($M_\\textrm{a} / M_\\textrm{d}$)", fontsize=10)
plt.colorbar(
    c,
    ax=axs,
    orientation="vertical",
    location="right",
    label=r"Final period (days)",
)
plt.yticks(
    [0.7, 0.66, 0.63, 0.6, 0.5, 0.44, 0.4][::-1], [f"{q:.2f}" for q in grid.axes["q"]]
)

plt.savefig("/home/koen/LaTeX-setup/plots/w24-grid-period-days.pgf", format="pgf")
plt.show()
plt.close()


# %%
import matplotlib


def z(r):
    try:
        r.period_days[-1]
    except IndexError:
        return np.nan

    if r.envelope_mass[-1] > 1e-2:
        if r.period_days[-1] < 50:
            return 0.5
        else:
            return 0

    return 1


from matplotlib.colors import ListedColormap

# Let's also design our color mapping: 1s should be plotted in blue, 2s in red, etc...
col_dict = {
    0: "C3",
    0.3: "C1",
    0.6: "C2",
}

# We create a colormar from our list of colors
cm = ListedColormap([col_dict[x] for x in col_dict.keys()])

# Let's also define the description of each category : 1 (blue) is Sea; 2 (red) is burnt, etc... Order should be respected here ! Or using another dict maybe could help.
labels = np.array(["Convergence problems", "Darwin Instability", "Completed"])
len_lab = len(labels)
# prepare normalizer
# Prepare bins for the normalizer
norm_bins = np.sort([*col_dict.keys()]) + 0.5
norm_bins = np.insert(norm_bins, 0, np.min(norm_bins) - 1.0)
print(norm_bins)
# Make normalizer and formatter
norm = matplotlib.colors.BoundaryNorm(norm_bins, len_lab, clip=True)


fig, axs = plt.subplots(
    2,
    2,
    sharey=True,
    sharex=True,
    figsize=set_size(full, height=1),
    constrained_layout=True,
)

axs = axs.flatten()

minn = 1e99
maxx = -1e99


R, q, ratio = grid.array(z, x="R", y="q")

minn = np.nanmin(ratio) if np.nanmin(ratio) < minn else minn
maxx = np.nanmax(ratio) if np.nanmax(ratio) > maxx else maxx

ms = [1.8, 2.2, 2.6, 3.0]

for i, ax in enumerate(axs):

    ax.set_title(f"$M_\\textrm{{TPAGB}} = {ms[i]:.1f}\\;M_\\odot$")
    R, q, ratio = grid.array(z, x="R", y="q", m=ms[i])

    c = axs[i].pcolormesh(
        R,
        q,
        ratio.T,
        shading="auto",
        cmap=cm,
        vmin=minn,
        vmax=maxx,
        rasterized=True,
    )


fig.supxlabel(r"Roche lobe radius ($R_\odot$)", fontsize=10)
fig.supylabel("$q$ ($M_\\textrm{a} / M_\\textrm{d}$)", fontsize=10)

fmt = matplotlib.ticker.FuncFormatter(lambda x, pos: labels[norm(x)])

plt.colorbar(
    c,
    ax=axs,
    orientation="horizontal",
    location="top",
    aspect=50,
    ticks=[0.333 / 2, 0.5, 1 - 0.333 / 2],
    format=fmt,
    shrink=0.5,
)
plt.yticks(
    [0.7, 0.66, 0.63, 0.6, 0.5, 0.44, 0.4][::-1], [f"{q:.2f}" for q in grid.axes["q"]]
)

plt.savefig("/home/koen/LaTeX-setup/plots/w24-grid-fate.pgf", format="pgf")
plt.show()
plt.close()


# %%


def z(r):
    try:
        r.period_days[-1]
    except IndexError:
        return np.nan

    if r.envelope_mass[-1] > 1e-2:
        return np.nan

    return r.star_2_mass[-1]


fig, axs = plt.subplots(
    2,
    2,
    sharey=True,
    sharex=True,
    figsize=set_size(full, height=1),
    constrained_layout=True,
)

axs = axs.flatten()

minn = 1e99
maxx = -1e99


R, q, ratio = grid.array(z, x="R", y="q")

minn = np.nanmin(ratio) if np.nanmin(ratio) < minn else minn
maxx = np.nanmax(ratio) if np.nanmax(ratio) > maxx else maxx

ms = [1.8, 2.2, 2.6, 3.0]

for i, ax in enumerate(axs):

    ax.set_title(f"$M_\\textrm{{TPAGB}} = {ms[i]:.1f}\\;M_\\odot$")
    R, q, ratio = grid.array(z, x="R", y="q", m=ms[i])

    c = axs[i].pcolormesh(
        R,
        q,
        ratio.T,
        shading="auto",
        cmap="viridis",
        vmin=minn,
        vmax=maxx,
        rasterized=True,
    )


fig.supxlabel(r"Roche lobe radius ($R_\odot$)", fontsize=10)
fig.supylabel("$q$ ($M_\\textrm{a} / M_\\textrm{d}$)", fontsize=10)
plt.colorbar(
    c,
    ax=axs,
    orientation="horizontal",
    location="top",
    aspect=50,
    label=r"Final envelope mass ($M_\odot$)",
)
plt.yticks(
    [0.7, 0.66, 0.63, 0.6, 0.5, 0.44, 0.4][::-1], [f"{q:.2f}" for q in grid.axes["q"]]
)

# plt.savefig("/home/koen/LaTeX-setup/plots/w24-grid-envelope-mass.pgf", format="pgf")
plt.show()
plt.close()

# %%
rng = np.random.default_rng(seed=121)
models = rng.permutation(grid.models)
for model in models:

    if model.envelope_mass[-1] > 0.01:
        if model.envelope_mass[-1] < 0.2:
            print(model.params)
            break

# %%
plt.plot(model.age, model.R)
plt.plot(model.age, model.rl_1)
plt.show()

# %%

m = mr.MesaData(
    f"/home/koen/master-internship/mesa-models/test-grid-fixes-2026-08-18/R1100.00_q0.651_eps0.250_delta0.200_M2.6/LOGS/TPAGB/history.data"
)

# %%

plt.plot(m.elapsed_time, m.envelope_mass)
plt.show()
# %%

plt.plot(m.age, m.R)
plt.show()
# %%

star = get_star(m=2.6)
plt.plot(
    star.age[star.ntpagb :] - star.age[star.ntpagb],
    np.diff(star.age[star.ntpagb - 1 :]),
)
plt.plot(m.age, 10**m.log_dt)
plt.show()
# %%


def get_mass_limit(envelope_mass):
    return np.clip(envelope_mass * 1e-4, a_min=7.5e-6, a_max=1e-3)


plt.plot(star.m_env, get_mass_limit(star.m_env))
plt.plot(star.m_env[1:], -np.diff(star.mass))
plt.show()
# %%

1 / 1e-4
0.1 / 1e-5
# %%

plt.plot(star.m_env, get_mass_limit(star.m_env))
plt.plot(m.envelope_mass[1:], -np.diff(m.star_mass) / 10)
plt.show()
# %%

fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

env_mass = np.logspace(-3, 1, 300)
plt.plot(env_mass, get_mass_limit(env_mass))
plt.xscale("log")
plt.yscale("log")


axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Envelope mass ($M_\odot$)")
plt.ylabel(r"\texttt{delta\_lg\_star\_mass\_limit}")
plt.savefig("/home/koen/LaTeX-setup/plots/w24-lgdmass.pgf", format="pgf")
plt.show()
plt.close()
# %%


fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(full, height=0.2), constrained_layout=True
)


plt.plot(m.envelope_mass[1:], (np.diff(m.R) / 10) / (np.diff(m.age) / 10))

unique_counts = np.unique(m.TP_count)

plt.xscale("log")
plt.xlim(axs.get_xlim())
for c in unique_counts:
    ind = np.argwhere(m.TP_count == c)[0][0]
    plt.axvline(m.envelope_mass[ind], c="C9", linewidth=0.75, zorder=-10)

axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Envelope mass ($M_\odot$)")
plt.ylabel(r"$\textrm{d}R / \textrm{d}t$")
plt.ylim(-50, 100)
plt.savefig(
    "/home/koen/LaTeX-setup/plots/w24-radius-pulsations-after-fix.pgf", format="pgf"
)
plt.show()
plt.close()

# %%
model.bulk_names
# %%

for model in grid.filter(q=[0.6, 0.7]):

    plt.plot(model.envelope_mass, model.num_retries)

plt.show()
# %%
rng = np.random.default_rng(seed=10000)
models = rng.permutation(grid.models)
for model in models:

    if model.envelope_mass[-1] > 0.01:
        if model.envelope_mass[-1] < 0.2:
            print(model.params)
            break

plt.plot(model.age, model.R)
plt.plot(model.age, model.rl_1)
plt.show()

# %%
plt.plot(model.envelope_mass, model.R)
plt.plot(model.envelope_mass, model.rl_1)
plt.plot(m.envelope_mass, m.R)
plt.plot(m.envelope_mass, m.rl_1)
plt.show()


# %%

m = mr.MesaData(
    f"/home/koen/master-internship/mesa-models/test-grid-fixes-2026-08-18/R800.00_q0.429_eps0.250_delta0.200_M3.0/LOGS/TPAGB/history.data"
)


# %%

plt.plot(star.m_env, get_mass_limit(star.m_env))
plt.plot(m.envelope_mass[1:], -np.diff(m.star_mass) / 10)
plt.show()

# %%
rng = np.random.default_rng(seed=20000)
models = rng.permutation(grid.models)
for model in models:

    if model.envelope_mass[-1] > 0.01:
        if model.envelope_mass[-1] < 0.2:
            print(model.params)
            break

plt.plot(model.age, model.R)
plt.plot(model.age, model.rl_1)
plt.show()


# %%

m = mr.MesaData(
    f"/home/koen/master-internship/mesa-models/test-grid-fixes-2026-08-18/R600.00_q0.651_eps0.250_delta0.200_M2.6/LOGS/TPAGB/history.data"
)


# %%

plt.plot(star.m_env, get_mass_limit(star.m_env))
plt.plot(m.envelope_mass[1:], -np.diff(m.star_mass) / 10)
plt.show()


# %%
plt.plot(model.envelope_mass, model.R)
plt.plot(model.envelope_mass, model.rl_1)
plt.plot(m.envelope_mass, m.R)
plt.plot(m.envelope_mass, m.rl_1)
plt.show()


# %%
fig, axs = plt.subplots(
    1, 1, sharex=True, figsize=set_size(column), constrained_layout=True
)

norm = plt.Normalize(0.4, 0.7)
cmap = plt.cm.viridis
# color = cmap(norm(x))


for model in grid.filter(m=1.8, R=[900, 1000]):
    (l1,) = plt.plot(
        model.age, model.R, c="C9", linewidth=0.75, zorder=-10, label="Star radius"
    )
    (l2,) = plt.plot(
        model.age,
        model.rl_1,
        c=cmap(norm(model.params["q"])),
        label="Roche lobe radius",
    )


sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])

cbar = plt.colorbar(sm, ax=plt.gca())
cbar.set_label(r"$q_\textrm{i}$")

fig.legend(handles=[l1, l2], loc="outside upper center", ncols=2)


axs.spines[["right", "top"]].set_visible(False)
plt.xlabel("Time (yr)")
plt.ylabel("Radius ($R_\odot$)")
plt.savefig("/home/koen/LaTeX-setup/plots/.pgf", format="pgf")
plt.show()
plt.close()
# %%
